Vinnyumc/Vinny-backend

src/main/java/com/vinny/backend/Common/domain/BaseEntity.java
=> [Feat/#5] Common domain BaseEntity 생성 (진짜)

src/main/java/com/vinny/backend/Common/domain/BaseEntity.java
=> [Feat/#5] Common domain BaseEntity 생성

src/main/java/com/vinny/backend/Common/domain/BaseEntity.java, src/main/java/com/vinny/backend/Shop/domain/RegionCategory.java, src/main/java/com/vinny/backend/Shop/domain/Shop.java, src/main/java/com/vinny/backend/Shop/domain/ShopStyle.java, src/main/java/com/vinny/backend/Shop/domain/Style.java, src/main/java/com/vinny/backend/Shop/domain/enums/Status.java, src/main/java/com/vinny/backend/Shop/domain/id/ShopStyleId.java
RegionCategory, Shop, ShopStyle, Style 엔티티와 필요한 클래스를 작성하였습니다.
=> ✨ [Feat/#4] Shop 관련 엔티티 작성

src/main/java/com/vinny/backend/error/ApiResponse.java
=> 🐛[Fix/#25] ApiResponse 성공한 경우 응답 생성 주석 해제

src/main/java/com/vinny/backend/post/domain/Like.java
=> 🐛[Fix/#23] Like 클래스 User 임포트 추가

src/main/java/com/vinny/backend/Shop/domain/ShopImage.java
- close #29 
기존에 shop 대표이미지만 필드에 있어, 따로 ShopImage를 만들어 디자인에 있는 여러 사진을 담을 수 있게 합니다.
- 
-
=> ✨[Feat/#29] ShopImage 테이블 추가

src/main/java/com/vinny/backend/User/domain/User.java, src/main/java/com/vinny/backend/User/domain/enums/UserShopStatus.java, src/main/java/com/vinny/backend/User/domain/mapping/UserFavorite.java, src/main/java/com/vinny/backend/User/domain/mapping/UserShop.java
=> ✨[Feat/#33] UserShop 엔티티 추가

src/main/java/com/vinny/backend/Shop/domain/ShopImage.java
- close #38 
ShopImage에서 isMainImage의 columnDefinition = "TINYINT(1) DEFAULT 0" 제거
=> 🐛[Fix/#38] ShopImage H2 문법 오류

src/main/java/com/vinny/backend/Shop/controller/ShopController.java, src/main/java/com/vinny/backend/Shop/dto/ShopSearchResponseDto.java, src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java, src/main/java/com/vinny/backend/Shop/service/ShopService.java, src/main/java/com/vinny/backend/config/SecurityConfig.java, src/main/java/com/vinny/backend/post/controller/PostController.java, src/main/java/com/vinny/backend/post/domain/Post.java, src/main/java/com/vinny/backend/post/dto/PostSearchResponseDto.java, src/main/java/com/vinny/backend/post/repsitory/PostRepository.java, src/main/java/com/vinny/backend/post/service/PostService.java
- close #45 
- 스웨거 api 명세를 위한 코드 구현
-  controller 와 Dto를 구현했습니다
=> ✨ [Feat/#45] 검색 기능 api Controller 및 DTO 구현

src/main/java/com/vinny/backend/Shop/controller/ShopController.java, src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java, src/main/java/com/vinny/backend/Shop/domain/Shop.java, src/main/java/com/vinny/backend/Shop/domain/ShopImage.java, src/main/java/com/vinny/backend/Shop/domain/mapping/ShopVintageStyle.java, src/main/java/com/vinny/backend/Shop/dto/ShopRequestDto.java, src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java, src/main/java/com/vinny/backend/Shop/repository/ShopImageRepository.java, src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java, src/main/java/com/vinny/backend/Shop/service/ShopCommandService.java, src/main/java/com/vinny/backend/Shop/service/ShopCommandServiceImpl.java, src/main/java/com/vinny/backend/User/repository/RegionRepository.java, src/main/java/com/vinny/backend/User/repository/VintageStyleRepository.java, src/main/java/com/vinny/backend/User/validation/annotation/ExistRegion.java, src/main/java/com/vinny/backend/User/validation/annotation/ExistVintageStyle.java, src/main/java/com/vinny/backend/User/validation/validator/RegionExistValidator.java, src/main/java/com/vinny/backend/User/validation/validator/VintageStyleExistValidator.java
=> [Feat/#41] 가게 생성 api

.github/workflows/dev_deploy.yml
=> 🔧[Chore/#52] CI/CD 스크립트 추가

src/main/java/com/vinny/backend/post/controller/PostController.java, src/main/java/com/vinny/backend/post/converter/PostConverter.java, src/main/java/com/vinny/backend/post/domain/Post.java, src/main/java/com/vinny/backend/post/domain/mapping/PostBrandHashtag.java, src/main/java/com/vinny/backend/post/domain/mapping/PostShopHashtag.java, src/main/java/com/vinny/backend/post/domain/mapping/PostStyleHashtag.java, src/main/java/com/vinny/backend/post/domain/mapping/UserPost.java, src/main/java/com/vinny/backend/post/dto/PostResponseDto.java, src/main/java/com/vinny/backend/post/repository/PostRepository.java, src/main/java/com/vinny/backend/post/service/PostService.java
=> ✨[Feat/#48] 피드 전체 조회 api 

src/main/java/com/vinny/backend/notification/domain/Notification.java
- close #54 
게시글에 대한 좋아요 알림 기능 추가로인해 기능구현에 필요한 엔티티를 생성했습니다
- erd 수정
-notification 엔티티 추가
그럴일 없대서 최대한 단순한 형태로 만들었는데 
만약 좋아요 알림외에 다른 알림 기능도 추가된다면 구조를 바꿀 필요할 수도 있을 듯합니다
=> ✨[feat/#54] 알림 엔티티 생성

src/main/java/com/vinny/backend/Shop/controller/ShopController.java, src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java, src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java, src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java, src/main/java/com/vinny/backend/Shop/service/ShopService.java, src/main/java/com/vinny/backend/User/repository/VintageStyleRepository.java, src/main/java/com/vinny/backend/User/validation/validator/VintageStyleExistValidator.java, src/main/java/com/vinny/backend/common/validator/ValidPageParam.java, src/main/java/com/vinny/backend/common/validator/ValidPageParamResolver.java, src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
- close #49 
스타일별 가게 목록 조회 (페이징) api
=> ✨[Feat/#49] 스타일별 가게 목록 조회 (페이징) api

.gitignore, src/main/resources/application-local.yaml
- close #63 
- env 및 application-yml 파일 관리
- 민감한 정보는 .env 파일을 따로 만들어서 관리를 하시면 될 것 같습니다! yml파일은 다시 만들어두도록 하겠습니다!
- env 코드는 notion gitignore 페이지에 따로 만들어두곘습니다
=> 🔧[Chore/#63] .env 파일 및 application.yml 환경변수 관리 개선

.github/workflows/dev_deploy.yml
=> 🔧[Chore/#56] dev_deploy 수정

.github/workflows/dev_deploy.yml, Dockerfile
- close #
dev_deploy, Dokerfile 수정
=> 🔧[Chore/#68] CI/CD 파일 수정

.github/workflows/dev_deploy.yml
- close #
dev_delpoy.yml v3 -> v4 수정
=> 🔧[Chore/#71] CI/CD 파일 수정- dev_deploy.yml

.github/workflows/dev_deploy.yml, src/main/resources/application-local.yaml
=> 🔧[Chore/#85] aws-jwt-secret 추가

src/main/java/com/vinny/backend/Shop/controller/ShopController.java, src/main/java/com/vinny/backend/Shop/service/ShopService.java, src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java, src/main/resources/application-local.yaml
=> ✨[Feat/#59] 가게 상세 조회 api

build.gradle, src/main/java/com/vinny/backend/User/controller/UserController.java, src/main/java/com/vinny/backend/User/domain/User.java, src/main/java/com/vinny/backend/User/domain/enums/Provider.java, src/main/java/com/vinny/backend/User/domain/enums/UserStatus.java, src/main/java/com/vinny/backend/User/dto/OnboardingRequestDto.java, src/main/java/com/vinny/backend/User/repository/BrandRepository.java, src/main/java/com/vinny/backend/User/repository/RegionRepository.java, src/main/java/com/vinny/backend/User/repository/UserRepository.java, src/main/java/com/vinny/backend/User/repository/VintageItemRepository.java, src/main/java/com/vinny/backend/User/repository/VintageStyleRepository.java, src/main/java/com/vinny/backend/User/service/UserService.java, src/main/java/com/vinny/backend/User/validation/annotation/ExistingBrandIds.java, src/main/java/com/vinny/backend/User/validation/annotation/ExistingRegionIds.java, src/main/java/com/vinny/backend/User/validation/annotation/ExistingVintageItemIds.java, src/main/java/com/vinny/backend/User/validation/annotation/ExistingVintageStyleIds.java, src/main/java/com/vinny/backend/User/validation/validator/ExistingBrandIdsValidator.java, src/main/java/com/vinny/backend/User/validation/validator/ExistingRegionIdsValidator.java, src/main/java/com/vinny/backend/User/validation/validator/ExistingVintageItemIdsValidator.java, src/main/java/com/vinny/backend/User/validation/validator/ExistingVintageStyleIdsValidator.java, src/main/java/com/vinny/backend/auth/controller/AuthController.java, src/main/java/com/vinny/backend/auth/dto/KakaoTokenRequestDto.java, src/main/java/com/vinny/backend/auth/dto/KakaoUserResponse.java, src/main/java/com/vinny/backend/auth/dto/LoginResponseDto.java, src/main/java/com/vinny/backend/auth/jwt/AppleJwtUtils.java, src/main/java/com/vinny/backend/auth/jwt/JwtProvider.java, src/main/java/com/vinny/backend/auth/service/AuthService.java, src/main/java/com/vinny/backend/auth/service/KakaoAuthService.java, src/main/resources/application-local.yaml
- #66 
- JWT Subject를 User 엔티티의 id로 수정했습니다.
- 카카오 로그인 연동 완료했습니다.
- 프런트에서 카카오에서 발급한 AccessToken을 /login/kakao API로 넘기면 JWT의 AccessToken과 RefreshToken이 발급되는 구조입니다.
- JWT AccessToken을 사용해 onboarding API를 호출할 수 있습니다.
- Onboarding api 구현 1차 완료했습니다. (추가 테스트 예정입니다.)
- 애플 로그인 연동 예정입니다.
- 카카오 관련 키는 비니 노션 .env에 추가해두었습니다.
- 데이터베이스에 해당하는 id가 없으면 예외처리 -> api 호출 실패
---
- 조건을 맞추는 경우에만 데이터베이스에 잘 올라감
=> ✨[Feat/#66] KakaoAuth + Onboard api 구현

src/main/java/com/vinny/backend/User/controller/UserShopController.java, src/main/java/com/vinny/backend/User/domain/mapping/UserShop.java, src/main/java/com/vinny/backend/User/dto/UserShopRequestDto.java, src/main/java/com/vinny/backend/User/dto/UserShopResponseDto.java, src/main/java/com/vinny/backend/User/repository/UserShopRepository.java, src/main/java/com/vinny/backend/User/service/UserShopService.java, src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
- close #102
1. 찜 추가
2. 찜 목록 조회 (나)
3. 찜 목록 조회 (다른 사용자)
4. 찜 삭제
인증에서 userId 가져오게 서비스 작업했습니다.
1. 찜 추가
2. 찜 목록 조회 (나)
3. 찜 목록 조회 (다른 사용자)
4. 찜 삭제
=> ✨[Feat/#102] 가게 즐겨찾기 관련 api

docker-compose.yml, src/main/resources/application-prod.yaml
- close #127 
- rds 연결 및 데이터베이스 경로 변경
- docker-compose 수정
- application-prod.yaml 추가
=> 🔧[Chore/#127] docker-compose 및 rds 설정 yaml 추가

src/main/java/com/vinny/backend/Shop/controller/ReviewController.java, src/main/java/com/vinny/backend/Shop/repository/ReviewRepository.java, src/main/java/com/vinny/backend/Shop/service/ReviewService.java, src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
- close #116
- 
-
3분전에 만든 리뷰를 잘 조회하고 있습니다.
삭제 테스트를 위해
삭제 후 다시 조회를 누르면
빈 리스트를 반환합니다.
=> ✨[Feat/#116] 가게 후기 조회, 삭제 api

src/main/java/com/vinny/backend/config/SecurityConfig.java
- close #141 
스웨거에서 API 호출할 때 CORS 위반 걸려서 403 에러 뜨는 오류 잡았습니다.
- 
-
=> 🔧[chore] CORS 허용 경로 추가

src/main/java/com/vinny/backend/Shop/controller/ReviewController.java, src/main/java/com/vinny/backend/Shop/controller/ShopController.java, src/main/java/com/vinny/backend/Shop/dto/ReviewRequestDto.java, src/main/java/com/vinny/backend/Shop/service/ShopService.java, src/main/java/com/vinny/backend/User/controller/UserShopController.java, src/main/java/com/vinny/backend/User/service/UserShopService.java, src/main/java/com/vinny/backend/common/validator/ValidPageParamResolver.java, src/main/java/com/vinny/backend/config/WebConfig.java, src/main/java/com/vinny/backend/error/code/status/ErrorStatus.java
- close #145
가게 관련 스웨거 설명 수정
가게 내 찜 조회 api 중복 삭제
상대방 프로필 조회가 토큰 없이 가능하면 /api/users 를 SecurityConfig에 추가해야 할 것 같습니다.
=> ♻️[Refactor/#145] 가게 관련 api 스웨거 수정 및 삭제

.github/workflows/dev_deploy.yml
- close #
- `docker rm -f vinny-app` 외에도 `docker-compose.yml` 존재 시 `docker compose down --remove-orphans` 실행 로직 추가
-  포트 해제 대기 로직(최대 30초) 삽입으로 Bind 실패 방지
-
=> 🐛 [fix]: cicd 배포 설정 수정 

src/main/java/com/vinny/backend/post/dto/PostResponseDto.java
- close #155 
응답에 유저 코멘트, 게시글 제목이 빠져있어서 추가했습니다
- 
-
=> 🐛[fix]  게시글상세 응답dto 수정

src/main/java/com/vinny/backend/User/repository/BrandRepository.java, src/main/java/com/vinny/backend/brand/controller/BrandController.java, src/main/java/com/vinny/backend/brand/dto/BrandDto.java, src/main/java/com/vinny/backend/brand/service/BrandService.java, src/main/java/com/vinny/backend/style/controller/StyleController.java, src/main/java/com/vinny/backend/style/dto/StyleDto.java, src/main/java/com/vinny/backend/style/repository/StyleRepository.java, src/main/java/com/vinny/backend/style/service/StyleService.java
- close #158 
- 
-게시글 작성 시 스타일 목록 조회 입니다
db에 존재하는 모든 스타일 목록을 오름차순으로 반환합니다
브랜드 검색은 미구현입니다
=> ✨[feat]게시글 작성시 목록 조회 및 검색

src/main/java/com/vinny/backend/User/domain/User.java, src/main/java/com/vinny/backend/User/dto/OnboardingRequestDto.java, src/main/java/com/vinny/backend/User/service/UserService.java
- close #163 
- 기존 온보딩 Request에서 닉네임과 코멘트를 추가했습니다.
=> 🐛 [fix] 온보딩 request 닉네임, 코멘트 추가

src/main/java/com/vinny/backend/Mypage/Controller/MypageController.java, src/main/java/com/vinny/backend/Mypage/Service/MypageService.java, src/main/java/com/vinny/backend/Mypage/dto/MypageBookmarkPostResponse.java, src/main/java/com/vinny/backend/post/repository/UserPostBookmarkRepository.java, src/main/java/com/vinny/backend/post/repository/UserPostLikeRepository.java
- close #178 
- dto로 반환하도록 수정
-
=> ♻️ [refactor] 마이페이지 저정한 게시글 dto로 반환하도록 수정

src/main/java/com/vinny/backend/Shop/domain/Shop.java
=> refactor: addressdetail column 추가

src/main/java/com/vinny/backend/auth/controller/AuthController.java
=> 🐛 [fix] AuthController 401 에러 처리 수정

src/main/java/com/vinny/backend/search/dto/ShopResponse.java
=> ♻️ [refactor] addressdetail dto 세부 삭제

src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java, src/main/java/com/vinny/backend/Shop/domain/ShopImage.java, src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java, src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java
=> ♻️[Refactor/#203] Shop image 필드 변경

src/main/java/com/vinny/backend/User/controller/UserShopForYouController.java
- close #211
/regenerate가 쓰이지 않아 제외했습니다.
=> ♻️[Refactor/#211] Home api /regenerate 제외

src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java, src/main/java/com/vinny/backend/Shop/domain/Shop.java, src/main/java/com/vinny/backend/Shop/dto/ShopResponseDto.java, src/main/java/com/vinny/backend/Shop/repository/ShopRepository.java
- close #215
shop entity logo_image 필드 추가 및 dto, converter 수정
=> [Feat/#215] shop entity logo_image 필드 추가 

src/main/java/com/vinny/backend/Shop/domain/Shop.java
- close #217
기존 logoImage의 길이가 VARCHAR(255)라서 다 들어가지 못한 URL이 존재해, 1024로 늘려주었습니다.
=> 🐛[Fix/#217] logoImage length 수정

src/main/java/com/vinny/backend/Shop/converter/ShopConverter.java, src/main/java/com/vinny/backend/Shop/service/ShopService.java
- close #229
- 찜 하지 않는 가게일 경우 에러가 나는 걸 수정했습니다
=> [Refactor/#229] 가게 상세 조회 수정

src/main/java/com/vinny/backend/auth/service/AuthService.java
=> fix: 로그아웃 유저상태 온보딩으로 임시 수정
